<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="WebFormSample.Index" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="gv" runat="server" CssClass="table table-striped" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="gv_PageIndexChanging">

    </asp:GridView>
</asp:Content>
